### ISSUE TITLE
QuickMap RDP mapping not working for regular users

### ISSUE THREAD

**Issue by rodrigo-hissam** [Ylianst/MeshCentralRouter#100] opened 2024-09-11 17:00 UTC
Describe the bug
After a regular user logs into meshrouter and tries to do a quickmap RDP launch, no action is taken as the quickmap silently fails. Launching meshrouter in debug mode we can see this:

ExceptionSink: System.NullReferenceException: Object reference not set to an instance of an object.
at MeshCentralRouter.MainForm.QuickMap(Int32 protocol, Int32 port, Int32 appId, NodeClass node)
at MeshCentralRouter.MainForm.rdpToolStripMenuItem_Click(Object sender, EventArgs e)
at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ToolStrip.WndProc(Message& m)
at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

To Reproduce

As a regular user, right click the device you want to RDP into and choose RDP
No RDP mapping is created, so nothing happens to the user
Expected behavior
An automatic mapping should be created and the RDP launch windows should appear.

Server Software (please complete the following information):

OS: Ubuntu 24.04.1
Version: MeshCentral v 1.29.1
Node: v19.8.1
Additional context
Admin users can still use meshrouter normally, only regular users seem to not be able to use the quickmap function.

**Comment by si458** [comment] 2024-09-12 16:04
right so indeed the issue is to do with the meshcentralrouter

a work around is to get a user to login to the web ui, then click the RDP option when they select a device,
then let the browser open up meshcentralrouter and it works

but will look into it asap

**Comment by si458** [comment] 2024-09-12 17:31
@rodrigo-hissam @mcallisaya79 this should be fixed now.
please can you try this version? [MeshCentralRouter.zip](https://github.com/user-attachments/files/16983396/MeshCentralRouter.zip)
if it asks to update say NO

**Comment by rodrigo-hissam** [comment] 2024-09-12 17:44
@si458 Just did a quick test and the quickmap function seems be working once again in this version you linked.

![image](https://github.com/user-attachments/assets/c68b9425-2216-4cfd-8620-b581b06ffb31)

**Comment by si458** [comment] 2024-09-12 17:50
@rodrigo-hissam great thanks!
it was because it was checking if the device was in a group for relaying
but individual devices DONT have meshgroups as such
so hense it was erroring out!
also discovered an RDP bug where it was opening up multiple RDP ports over and over again,
rather than using the port that was already open, doh!

**Closed by si458** 2024-09-12 17:50 UTC
Labels: bug

**Comment by rodrigo-hissam** [comment] 2024-09-12 17:56
Thank you!! Will this end up being included in a new meshcentral release?

**Comment by si458** [comment] 2024-09-12 17:59
yes, ill will add it in later into the main repo so it will be available in the next release 👍 
in the mean time, you can copy and paste the exe from above into `node_modules/meshcentral/agents/`
then restart your meshcentral, and everytime other people open up there version, they will get an update alert
and it will download the new version u patched from above 👍

**Comment by rodrigo-hissam** [comment] 2024-09-12 18:23
Thank you once again @si458

**Comment by si458** [comment] 2024-09-12 18:24
uploaded to main repo too ready for next release!
PS dont forget to donate if you can ❤️ https://www.si458.co.uk/2024/01/05/donation/
